### ISSUE TITLE
Research venmo or other payment option integration

### ISSUE THREAD

**Issue by lukefranc0** [CSC4790-Fall2024-Org/Grocery-Receipt-App#27]

**Comment by JadenBresciaVillanova** [comment]
Conducted Research Over Fall Break and Learned a Few Key Details regarding Venmo
1. There are only a few ways to implement it with React Native due to Auth Token demands
2.  Only Options for Us Are: Deep Linking on Phone or Custom, Complex Backend Setup 

Group Discussion on What Potential Paths we Could Take:
1. Deep Linking - From Divvy phone, you send out multiple requests thru looping through each person (The app would reload constantly pre-loading all the requests and the user would approve each one), Key Requirement: Would need Venmo username from each person
2. Add Contact Info during Break-up stage (open contact list, add people to receipt using contacts) - Then have multiple buttons on Venmo page, to send messages to each person with that contact info with the price/items using button on Divvy. We would send a venmo request link to the host, so this way you avoid manually entering each person's Venmo. 
3. No Contact Info during break-up stage - Add Contacts and associate bills with certain people then send custom venmo request link
